version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: gonow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "197911"
      MYSQL_DATABASE: go_now_blog
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
